services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/log:/var/log/nginx/
    networks:
      - vuanem-bi-portal

  backend:
    container_name: backend
    image: us-docker.pkg.dev/${PROJECT_ID}/gcr.io/vuanem-bi-portal/backend:master
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/service-account.json:/tmp/service-account.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/service-account.json
    networks:
    - vuanem-bi-portal

  frontend:
    container_name: frontend
    image: us-docker.pkg.dev/${PROJECT_ID}/gcr.io/vuanem-bi-portal/frontend:master
    build: ./frontend
    networks:
    - vuanem-bi-portal

networks:
  vuanem-bi-portal:
