services:
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/log:/var/log/nginx/

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/service-account.json:/tmp/service-account.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/service-account.json
    ports:
      - 5000:5000

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env
    environment:
      NEXT_PUBLIC_API_URL: http://localhost/api
    ports:
      - "3000:3000"
