services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/log:/var/log/nginx/
    networks:
      - vuanem-bi-portal

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/service-account.json:/tmp/service-account.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/service-account.json
    networks:
    - vuanem-bi-portal

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend/.env.production:/app/.env.production
    networks:
    - vuanem-bi-portal

networks:
  vuanem-bi-portal:
