name: Build

on:
  workflow_call:
    inputs:
      base_name:
        required: true
        type: string
      base_dir:
        required: true
        type: string

env:
  NAME: vuanem-bi-portal
  PROJECT_ID: voltaic-country-280607

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-outputs.outputs.image }}
    steps:
      - id: set-outputs
        run: |
          echo "::set-output name=image::us-docker.pkg.dev/${{ env.PROJECT_ID }}/gcr.io/${{ env.NAME}}/${{ inputs.base_name }}:${{ github.ref_name }}"

  build:
    runs-on: ubuntu-latest
    needs: set-env
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: google-github-actions/setup-gcloud@v0

      - run: gcloud auth configure-docker us-docker.pkg.dev

      - uses: satackey/action-docker-layer-caching@v0.0.11

      - run: docker build --push -t ${{ needs.set-env.outputs.image }} ${{ inputs.base_dir }}
